### PR TITLE
Don't parse blank lines

### PR DESCRIPTION
**Pull request by mattbrun**
Don't parse blank lines. Useful to structure in a more clear way big ini files.

### CODE REVIEW

**Comment by seangarner** [comment]
This would be nice.  As a workaround I've been commenting an empty line.  e.g.

```
[cats]
; make the cats funny
funny = false
;
; make the cats crazy
crazy = catnip
```

Which gives you

```
iniparser.parseSync('file.ini').cats.crazy
// "catnip"
```

**Comment by mattbrun** [comment]
@seangarner your point is totally correct!
On the other hand, in my case I've .ini files hundreds lines long, so keep using ";" instead o blank lines doesn't keep the file easily readable and it's quite annoying too ;)

**Comment by shockie** [comment]
Do you have an example file to parse? I want to check if everything goes ok

**Comment by shockie** [comment]
I've updated the code, now the parse function will accept a options parameter. If you now call 

``` javascript
    parse(filename, {skip_blank_lines:true}, callback);
```

it will skip the blank lines a forces the parameters to be in a section. If the parameter is not in a section (this can happen if you have orphan parameters before any section is called), they will be placed in the DEFAULT section. 

You can check the change by cloning the develop branch, it will eventually land into the 1.1 version when everything is ok.

What do you guys think of it?

**Comment by seangarner** [comment]
Looks good to me. Not in front of a computer until Tuesday so I can't test
until then.

Thanks

**Comment by mattbrun** [comment]
@shockie thanks for the patch. I'll give it a try asap. Meanwhile, this is the example requested http://pastebin.com/Za3bGsJp

**Comment by mattbrun** [comment]
so, i tried out your solutions and it functions like a charm! :)
i close the pull request since is doesn't need to exist any more.

**Pull request closed without merging**
